# Study Premise

The Body Advocacy Movement (BAM) High Study (Phase 1: 2022-2023) is a pilot study investigating the feasibility, acceptability, and preliminary efficacy of an eating disorder risk reduction intervention within high school students developed by the EMBARK lab in 2022.

While existing, dissonance programs (i.e. the Body Project) target reductions in thin-ideal internalization, fears related to fatness and weight gain may be a particularly salient cognitive target among those with current or past eating disorder symptomatology (@levinsonAddressingFearFat2014). Past studies have demonstrated the high school population (youth ages 14-18) to be especially susceptible to the development of eating disorders like anorexia nervosa (AN) and bulimia nervosa (BN) (@kohnEatingDisordersChildren2001). In an effort to mitigate risk for ED onset and minimize the development of EDs among late adolescents, the current project includes development and initial evaluation of a novel intervention that focuses specifically on fear of fatness and anti-fat bias (the Body Advocacy Movement in High Schools; BAM High).

This project aims to recruit 30 high school students (ages 14-18) to all participate in the BAM High intervention. Our objective is to examine the degree to which BAM can reduce fear of fatness and weight gain along with internalized anti-fat bias and reduce risk and development ED symptoms in a late adolescent sample. We will evaluate feasibility and acceptability of BAM High and estimate effects of the intervention on self-report and behavioral measures of fear of weight gain and fatness, anti-fat bias, and eating disorder symptoms.

## Specific Aims

Aim 1: Examine the acceptability and feasibility of BAM in a high-risk young adult sample. Acceptability: Acceptability will be assessed via attrition across a 4-session intervention along with qualitative feedback from a brief survey at post-intervention. We expect to meet benchmarks of high acceptability (average ratings of > 4 [out of 5] on post-intervention survey; < 20% attrition). Feasibility: Feasibility will be benchmarked via intervention adherence (average competency > 8.0 on 0-10 scale) and recruitment goals.

Aim 2: Estimate the effects of the intervention on fear of fatness, anti-fat bias, and eating disorder symptoms. We hypothesize that the BAM intervention will result in acute reductions (post-intervention) in fatphobia and anti-fat bias across self—report and behavioral measures, outperforming the Body Project on targets related to anti-fat bias, specifically.
