# Study Premise

The Body Advocacy Movement (BAM) High Study (Phase 1: 2022-2023) is a pilot study investigating the feasibility, acceptability, and preliminary efficacy of an eating disorder risk reduction intervention within high school students developed by the EMBARK lab in 2022.

While existing, dissonance programs (i.e. the Body Project) target reductions in thin-ideal internalization, fears related to fatness and weight gain may be a particularly salient cognitive target among those with current or past eating disorder symptomatology (@levinsonAddressingFearFat2014). Past studies have demonstrated the high school population (youth ages 14-18) to be especially susceptible to the development of eating disorders like anorexia nervosa (AN) and bulimia nervosa (BN) (@kohnEatingDisordersChildren2001). In an effort to mitigate risk for ED onset and minimize the development of EDs among late adolescents, the current project includes development and initial evaluation of a novel intervention that focuses specifically on fear of fatness and anti-fat bias (the Body Advocacy Movement in High Schools; BAM High).

This project aims to recruit 30 high school students (ages 14-18) to all participate in the BAM High intervention. Our objective is to examine the degree to which BAM can reduce fear of fatness and weight gain along with internalized anti-fat bias and reduce risk and development ED symptoms in a late adolescent sample. We will evaluate feasibility and acceptability of BAM and estimate effects of the intervention on self-report and behavioral measures of fear of weight gain and fatness, anti-fat bias, and eating disorder symptoms.

## Specific Aims

**Aim 1:** Confirm the feasibility and acceptability of a fatphobia and weight stigma intervention. We will confirm the feasibility and acceptability of our intervention structure and content via (a) study attrition at all timepoints, (b) participant attendance to the 4 sessions, (c) completion rates of study activities both prior to and following sessions, and (d) intervention adherence and facilitator competence. To assess intervention adherence and facilitator competence, sessions will be audio recorded and reviewed by two members of research staff using a 12-item leader competence assessment. Over the course of the study, we expect study attrition to be \<20%, attendance at all 4 sessions to be \>80%, and completion rates of study activities to be \>75%. Feasibility will be benchmarked via two primary outcomes: (a) we expect high levels of intervention adherence in the intervention, with high interrater reliability and average treatment fidelity and facilitator competence ratings at or above 8.0 on a 10-point scale, and (b) we expect to meet recruitment goals (N = 30).

**Aim 2:** *Estimating intervention effects.* Reductions in anti-fat bias will be assessed via changes in self-report fatphobia and anti-fat bias as well as shifts in IAT and AAT task performance from baseline to post-intervention and baseline to 4-week follow-up. To evaluate changes over time for the singular group, we would use a paired t-test to assess if the intervention changed participants' cognitions about fatphobia and weight stigma.

**Aim 3:** *Eating Disorder Prevention.* Reductions in eating disorder symptomology will be assessed via changes in self-report eating disorder behaviors and cognitions from baseline to post-intervention and baseline to 4-week follow-up. We will specifically assess how the intervention has affected participants that have been identified as demonstrating disordered eating (ED) at baseline. To evaluate changes over time between the ED and healthy group, we will use mixed effects modeling, estimating fixed effects of Condition, Time, and a Time x Condition interaction, with a random intercept of participant to account for baseline differences.
