# Intervention

## The Body Advocacy Movement
BAM leverages both dissonance and exposure-based intervention strategies, adapting common exercises used to promote body acceptance and challenge sociocultural body ideals to specifically target anti-fat bias and internalized fatphobia. Participants in BAM will (1) Define anti-fat bias and fatphobia and explore how these constructs manifest in personal beliefs and interpersonal interactions, (2) Engage in imaginal exposure exercises to challenge fears related to fatness and weight gain (3) Reflect on how fears of fatness align with personal values, (4) Learn new ways to challenge fear of fatness and internalized anti-fat bias and (5) Discuss ways to challenge anti-fat bias on an institutional and societal level. Intervention content. 

### Session 1 
Session 1 includes introductions, discussing identities and clarifying terminology, and an exercise in defining anti-fat bias and fatphobia.  

### Session 2
Within Session 2 participants will be asked to complete an imaginal exposure exercise several times during the week in which they will write and then recount a ‘worst-case scenario’ of what they might fear could happen if they gained a significant amount of weight.

##Session 3 
Session 3 includes debriefing the exposure homework and identification of ways one might uproot internalized fear of fatness, along with a series of role plays in which peer facilitators will play the role of a friend or family member in a situation that evokes anti-fat attitudes, and participants will practice challenging these attitudes.

## Session 4 
Within session 4, participants will also identify ways to challenge anti-fat bias in society and commit to engaging in one activity to do so in the coming week. As an exit exercise, they will  write a ‘response letter’ to their worst-case scenario. 

## Peer Facilitators
The facilitators are all, at a minimum, graduate-level mental health providers. Each facilitator will participate in an 8-hour training program, similar to @sticeClinicianLedPeerLedInternetDelivered2017. Facilitators will role-play delivery of the entire intervention and observe other facilitators in doing the same. Facilitators will be supervised by Dr. Schaumberg. 


## Intervention Fidelity
Sessions will be audio recorded and reviewed by two members of research staff. Audio recorded sessions will be rated for fidelity and competence. Research staff will independently code a randomly selected sample of 50% of sessions for implementation fidelity and facilitator competence using checklists assessing the major exercises and discussion topics for each session. Each component will be rated for degree of accurate presentation (10-point scale from “No adherence; the section was skipped” to “Perfect; all material in the section was presented as written”). Facilitator competence will be rated using 12 items assessing indicators of competence (e.g., leaders express ideas clearly and at an appropriate pace, leaders attempt to allot equal speaking time for all members) on a 10-point scale. 

