# Task-based Measures

## Weight Implicit Association Test (Weight IAT)

Weight-IAT task data is housed in its own (long-format) data set within the study database, with keys of `subject_id` and `timepoint`. 

The Weight-IAT is a validated measure of automatic, unconscious attitudes that has previously been used to evaluate implicit weight-related biases [@phelanImplicitExplicitWeight2014] The Weight-IAT compares the accuracy of, and time required to categorize images of larger-bodied and thinner people together with positively- and negatively-valanced words. Outcomes include reaction time and percentage of correct categorizations.

### Scoring 
The IAT scoring algorithm involves several steps, with a rigorous scoring procedure involving 12 specifications [@greenwaldUnderstandingUsingImplicit2003]

Steps include:

1. Using data from Blocks 3,4,6, and 7

2. Eliminate trials with latencies > 10,000 ms; eliminate subjects for whom more than 10% of trials have latency less than 300 ms

3. Use all remaining trials

4. No extreme-value treatment (beyond Step 2)

5. Compute mean of correct latencies for each block

6. Compute one pooled SD for all trials in blocks 3 & 6; another for blocks 4 & 7

7. Replace each error latency with block mean (computed in Step 5) + 600 ms

8. No transformation 

9. Average the resulting values for each of the four blocks

10. Compute two differences: B6 - B3 and B7 - B4

11. Divide each difference by its associated pooled- trials SD from Step 6

12. Average the two quotients from Step 11

R code used for cleaning Weight-IAT data prior to implementing the scoring algorithm is available [here - not yet available]().
R code for completing the scoring algorithm with cleaned data is available [here - not yet avaialble]()

### Key Variables

## Weight Based Approach Avoidance Task (Weight-AAT)
An interactive task will manipulate congruency between reward- and threat-related outcomes -- a task derived from @weaverSacrificingRewardAvoid2020. Participants learn, through trial-and-error, which of three responses, indicated as geometric shapes, to select to achieve a particular outcome. Critically, each response option is associated with a probability of both a reward outcome (points) and an additional outcome (i.e., images of body parts of those in larger bodies). The response-outcome contingencies (e.g., which option is most likely to lead to reward) switch throughout the task, such that half the time the option that is most likely to lead to reward is also most likely to lead to seeing large body images (Conflict Phase), and half the time the highest reward option is least likely to lead to seeing large body images (Congruent Phase) . Participants are instructed to earn as many points as possible (reward goals), allowing us to test biases in decision-making when large body images are likely. In each trial, participants would choose a shape, and, after a  delay (.5-.75s), the point outcome for that trial appeared under the image (presented for 1.5–2.5s) while the image remained on screen, indicating a positive or negative value (e.g., +5 or -7). Trials were separated by a fixation cross, presented for .5-1.5s. The type of image (trauma-related or neutral) and the direction of points (positive, negative) were experimentally manipulated to reflect probabilities that aligned with the type of phase. The number of points won/lost was randomly generated (range: 1-10). Task Phases were not counterbalanced in order to allow for initial task structure learning before the introduction to the Conflict Phase. 

On all trials, both outcomes (image type, point win/loss) had either an 80%, 50%, or 20% chance of occurring. The image type and point win/loss probabilities were independent from one another. Probabilities for each outcome for the left and right shape (circle and hexagon) were adjusted throughout the task to create the Conflict and Congruent Phases.

### Scoring 

#### Difference Score
We can also create a crude individual difference score to represent discrepancy between the two task phases (Mean Conflict Phase points - Mean Congruent Phase Points), with higher difference score reflecting a higher degree of conflict between the two phases. 

#### Linear Mixed Effects Model

Code for scoring the Weight-AAT using a Linear mixed Effects Model Approach is available [here - not yet available]()

Weight-AAT task data is housed in its own (long-format) data set within the study database, with keys of `subject_id` and `timepoint`. 

The Linear Mixed Effects Model uses trial-wise outcomes (i.e. modeling outcomes on all trials for each participant). Prior to analysis, predictors and outcomes are scaled for analysis including block, Phase (Conflict = -1, Congruent - 1), and Trial (z-scored within each block) and regressed on Total Points (scaled from 0 to 1). Trial is coded to account for learning within block (e.g. trial number 1-25 z-scored to represent linear learning throughout a trial). 

Ultimate outputs of this model would include a random intercept and random slope for Phase, Block, Trial, and their interactions to account for individual variability -- e.g: 
Points ~ Phase + Trial + Block + Phase * Trial + Phase * Block + Trial * Block + Phase * Trial * Block + Age + Gender + (1+Phase * Trial * Block|sub)

To examine BMI differences, a Phase * BMI and Phase * Trial * BMI interaction may also be introduced to the model

#### Drift Diffusion Modeling
xxx

### Key Variables

`aat_difference_score` : Difference between points obtained during the conflict phases vs. congruent phases of the task 

`aat_phase` : Trial Phase (Conflict = -1, Congruent = 1)

